config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'
  resources :todos, only: [:index, :show] do
    resources :todousers, only: [:create, :destroy]
  end
  root to: 'todos#index'
  devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :todousers
  has_many :users, through: :todousers
end

app/models/todouser.rb
class Todouser < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :todousers
   has_many :todos, through: :todousers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.limit(9)
  end

  def show
    @todo = Todo.find(params[:id])
    @ranking5 = Todouser.limit(5).where(todo_id: @todo.id).order(created_at: :asc)
    @users_todo_finish = Todouser.all.where(todo_id: @todo.id).order(created_at: :asc)
  end

end

app/controllers/todousers_controller.rb
class TodousersController < ApplicationController
  before_action :authenticate_user!
  def create
    @todo = Todo.find(params[:todo_id])
    @todouser = Todouser.new(todo: @todo, user:current_user, done: true)
    if @todouser.save
      redirect_to todos_index_path, notice: 'La tarea ha sido terminada'
    else
      redirect_to todos_index_path, alert: 'La tarea no ha podido ser terminada'
    end
  end

  def destroy
    @todo = Todo.find(params[:todo_id])
    @todouser = Todouser.find_by(todo: @todo, user: current_user, done:true)
    if Todouser.exists?(user_id: current_user.id, todo_id: @todo.id, done: true)
      @todouser.destroy
      redirect_to todos_index_path, alert: 'La tarea ya no esta terminada'
    else
      redirect_to todos_index_path, alert: 'La tarea no puedo cambiar de estado'
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/todousers_helper.rb
module TodousersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolistapp</title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar'%>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Bucket List del 18", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span class="nav-link"> Completados
            <%= Todouser.where(user_id: current_user.id, done: true).count %> / <%= Todo.all.count %>
          </span>
        </li>
        <li class="nav-item">
          <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <!-- el admin puede ver el listado de productos vendidos -->
      <% else %>
        <li class="nav-item">
          <%= link_to "Acceder", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/todos/index.html.erb
<div class="container">
  <div class="row">
    <% @todos.each do |todo| %>
      <div class="col">
        <div class="card" style="width: 18rem;">
            <% if user_signed_in? && current_user.todousers.find_by(todo_id: todo.id) %>
              <%= image_tag todo.photo, class: "card-img-top img-gray-filter" %>
            <% else %>
              <%= image_tag todo.photo, class: "card-img-top" %>
            <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to todo.title, todo_path(id: todo.id)%></h5>
            <p class="card-text">Creación: <%= time_ago_in_words(todo.created_at) %></p>
            <% if user_signed_in? %>
              <% if current_user.todousers.find_by(todo_id: todo.id) %>
                <%= link_to "Marcar como no listo", todo_todouser_path(todo, current_user), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%= link_to "Marcar como listo", todo_todousers_path(todo), method: :post, class: "btn btn-success" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="row">
      <div class="col 4">
        <div class="card" style="width: 18rem;">
          <%= image_tag @todo.photo, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= @todo.title %></h5>
            <p class="card-text">Creación: <%= time_ago_in_words(@todo.created_at) %></p>
          </div>
        </div>
      </div>

    <div class="col 4">
      <table class="table">
        <thead>
            <h2>Ranking: Los 5 primeros finalistas</h2>
          <tr>
            <th scope="col">Avatar</th>
            <th scope="col">Nombre</th>
          </tr>
        </thead>
        <tbody>
          <% @ranking5.each do |rank| %>
            <tr>
                <td><%= image_tag("https://cdn0.iconfinder.com/data/icons/faces-3/24/148-512.png", class: "avatar-img") %></td>
                <td><%= User.find_by(id: rank.user_id).name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col 4">
      <h2>Todos los finalistas</h2>
      <ul class="list-group">
        <% @users_todo_finish.each do |user| %>
        <li class="list-group-item"><%= User.find_by(id: user.user_id).name %> </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>